<?php
function queen_menu() {
    $items['queen'] = array(
        'title' => "Queen",
        'page callback' => 'drupal_get_form',
        'page arguments' => array('queen_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['attack'] = array(
        'title' => 'Attack',
        'page callback' => 'queen_attack',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    return $items;
}

function queen_form() {
    $form['start_x'] = array(
        '#title' => 'Start X',
        '#type' => 'textfield',
        '#description' => t('Please enter starting X coordinate.'),
    );
    $form['start_y'] = array(
        '#title' => 'Start Y',
        '#type' => 'textfield',
        '#description' => t('Please enter starting Y coordinate.'),
    );
    $form['end_x'] = array(
        '#title' => 'End X',
        '#type' => 'textfield',
        '#description' => t('Please enter ending X coordinate.'),
    );
    $form['end_y'] = array(
        '#title' => 'End Y',
        '#type' => 'textfield',
        '#description' => t('Please enter ending Y coordinate.'),
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Queen',
    );

    return $form;
}

function queen_form_submit($form, &$form_state) {
    $start_x = $form_state['values']['start_x'];
    $start_y = $form_state['values']['start_y'];
    $end_x = $form_state['values']['end_x'];
    $end_y = $form_state['values']['end_y'];
    $attack = "";

    if($start_x == $end_x && $start_y == $end_y) {
        $attack = "This is an impossible situation. Try again.";
    }

    if(abs($start_x - $start_y) == abs($end_x - $end_y)) {
        $attack = "In range.";
    } else {
        $attack = "Not in range";
    }

    $_SESSION['queen_result'] = $attack;

    $form_state['redirect'] = 'attack';
}

function queen_attack() {
    $answer = $_SESSION['queen_result'];
    return 'Here is the result' . $answer;
}
